# Model
_target_: src.model.forward.CRTMModel
_recursive_: false

# Optimizer function and parameters
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0005
  weight_decay: 0.0

# Learning rate scheduler
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.2
  patience: 3
  min_lr: 1.0e-6
  threshold: 0.0
  threshold_mode: abs

# Loss function
loss:
  _target_: src.loss.loss.CRPS

# Architecture
architecture:
  _target_: src.model.architecture.legacy.CRTMArchitecture
  nprofvars:
    _target_: builtins.len
    _args_:
      - ${data.use_prof_vars}
  nsurfvars:
    _target_: builtins.len
    _args_:
      - ${data.use_surf_vars}
  nmetavars:
    _target_: builtins.len
    _args_:
      - ${data.use_meta_vars}
  nlevels: ${data.nlevels}
  nnodes_bt: 512
  nhidden_bt: 3
  dropout_rate: 0.0
  bt_norm_max: ${data.bt_norm_max}
  bt_norm_min: ${data.bt_norm_min}
  std_output_activation_offset: 0.001
  std_scale_trainable: true

# Backward compatibility: old parameters format (not used with architecture specified)
parameters: null
