# Model
_target_: src.model.inverse.PINNverseOperator
_recursive_: false

# Optimizer function and parameters
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0005
  weight_decay: 0.000

# Learning rate scheduler
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.5
  patience: 3
  min_lr: 1.0e-6
  threshold: 0.0
  threshold_mode: abs

# Model parameters associated with the data (e.g., input/output dimensions)
parameters:
  n_lat: 1
  n_lon: 1
  n_scans: 1
  n_prof:
    _target_: builtins.int
    _args_:
      - _target_: builtins.len
        _args_:
          - ${data.stage.train.vars.prof.type}
  n_levels: 127
  n_pressure: 1
  n_cloud: 0
  prof_vars: ${data.stage.train.vars.prof.type}

# Loss function and parameters
loss:
  _target_: src.loss.loss.VarLoss
  forward_model:
    _target_: src.loss.loss.ForwardModel
    dtype: ${data.dtype}
    prof_norm: null
  lambda_obs: 0.
  lambda_model: 1.
  lambda_bcs: 1.
  loss_obs:
    _target_: src.loss.loss.MSE
  loss_model:
    _target_: src.loss.loss.MSE
  loss_bcs:
    _target_: src.loss.loss.MSE
  pressure_filter: ${data.pressure_filter.load}

# Architecture components
architecture:
  _target_: src.model.inverse.HydraResidualMLP
  # Positional encoding
  positional_encoding:
    _target_: src.model.architecture.encoding.RescaledPositionalEncoding
    d_input:
      _target_: numpy.sum
      _args_:
        -
          - ${model.parameters.n_lat}
          - ${model.parameters.n_lon}
          - ${model.parameters.n_scans}
          - ${model.parameters.n_pressure}
          - ${model.parameters.n_cloud}
  # Input layer
  input_layer:
    _target_: src.model.inverse.LinearBlock
    in_features: null  # Set by positional encoding
    out_features: 128
    layernorm:
      _target_: torch.nn.Identity
    activation:
      _target_: src.model.architecture.activation.Sine
    dropout_rate: 0.1
    init_func:
      _target_: src.model.inverse.SirenInit
  # Hidden layers
  hidden_n_layers: 2
  hidden_skip: false
  hidden_layer:
    _target_: src.model.inverse.LinearBlock
    in_features: 128
    out_features: 128
    layernorm:
      _target_: torch.nn.Identity
    activation:
      _target_: src.model.architecture.activation.Sine
    dropout_rate: 0.1
    init_func:
      _target_: src.model.inverse.SirenInit
  # Output layers
  output_skip: false
  output_n_heads: 1
  output_n_layers: 1
  output_layer:
    _target_: src.model.inverse.LinearBlock
    in_features: 128
    out_features:
      _target_: builtins.int
      _args_:
        -
          _target_: numpy.multiply
          _args_:
            - ${model.parameters.n_prof}
            - ${model.parameters.n_pressure}
    layernorm:
      _target_: torch.nn.Identity
    activation:
      _target_: torch.nn.Sigmoid
    dropout_rate: 0.0
    init_func:
      _target_: src.model.inverse.SirenInit
  output_final_layer: null
