# Model
_target_: inverse.model.model.PINNverseOperatorPCACycle
_recursive_: false

# Optimizer function and parameters
optimizer:
  # Function
  _target_: torch.optim.Adam
  # Learning rate
  lr: 0.0005
  # Weight decay (L2 regularization)
  weight_decay: 0.000

# Learning rate scheduler
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  # T_0: Number of iterations for the first restart
  T_0: 20
  # T_mult: Factor by which T_i increases after a restart
  T_mult: 1
  # eta_min: Minimum learning rate (the "floor")
  eta_min: 1.0e-6

# Model parameters associated with the data (e.g., input/output dimensions) and architecture
parameters:
  # Number of variables
  n_lat: 1
  n_lon: 1
  n_scans: 1
  n_prof:
    _target_: builtins.int
    _args_:
      - _target_: builtins.len
        _args_:
          - ${data.stage.train.vars.prof.type}
  n_levels: 127
  n_pressure: 127
  n_comp: ${preparation.pca.prof.input.n_comp}
  n_cloud: 0
  # Profile variables (input/output)
  prof_vars: ${data.stage.train.vars.prof.type}

# Loss function and parameters
loss_func:
  # Function
  _target_: inverse.model.loss.VarLossPCA # Load loss function
  # Forward model to compute the model equivalent of the observations
  forward_model:
    # Function
    _target_: inverse.model.loss.ForwardModel
    # Precision
    dtype: ${data.dtype}
    # Normalization for the profile variables
    prof_norm: null
  # Weights for observation (obs), model, and boundary condition (bcs) errors
  lambda_obs: 0.
  lambda_model: 1.
  lambda_bcs: 1.
  # Loss term for observations
  loss_obs:
    _target_: inverse.model.loss.MSE
  # Loss term for model variables
  loss_model:
    _target_: inverse.model.loss.MSE
  # Loss term for boundary conditions
  loss_bcs:
    _target_: inverse.model.loss.MSE

# Architecture components
architecture:
  # Positional encoding
  positional_encoding:
    _target_: inverse.model.architecture.encoding.RescaledPositionalEncoding
    d_input:
      _target_: numpy.sum
      _args_:
        -
          - ${model.parameters.n_lat}
          - ${model.parameters.n_lon}
          - ${model.parameters.n_scans}
  # Input layer
  input_layer:
    _target_: inverse.model.model.LinearBlock
    in_features: ${model.architecture.positional_encoding.d_input}
    out_features: ${model.architecture.hidden_layer.in_features}
    layernorm:
      _target_: torch.nn.Identity
    activation:
      _target_: inverse.model.architecture.activation.Sine
    dropout_rate: 0.1
    init_func:
      _target_: inverse.model.model.SirenInit
      is_first_layer: true
  # Hidden layer
  n_hidden_layers: 2
  hidden_skip: false
  hidden_layer:
    _target_: inverse.model.model.LinearBlock
    in_features: 128
    out_features: ${model.architecture.hidden_layer.in_features}
    layernorm: ${model.architecture.input_layer.layernorm}
    activation: ${model.architecture.input_layer.activation}
    dropout_rate: ${model.architecture.input_layer.dropout_rate}
    init_func:
      _target_: inverse.model.model.SirenInit
      is_first_layer: false
  # Output layer
  output_skip: false
  output_n_heads: 1
  output_layer:
    _target_: inverse.model.model.LinearBlock
    in_features: ${model.architecture.hidden_layer.out_features}
    out_features: ${model.parameters.n_comp}
    layernorm: ${model.architecture.input_layer.layernorm}
    activation:
      _target_: torch.nn.Identity
    dropout_rate: 0.0
    init_func:
      _target_: inverse.model.model.SirenInit
      is_first_layer: false
      is_head: true