# Inverse Model Configuration (refactored to use separate configs)
_target_: code.model.inverse.InverseModel
_recursive_: false

# Checkpoint path for saving and loading model weights
ckpt_path: ${paths.checkpoint_dir}/${callbacks.model_checkpoint.filename}.ckpt

# Optimizer - reference external config
optimizer: ${optimizer}

# Scheduler - reference external config
scheduler: ${scheduler}

# Loss function - reference external config
loss: ${loss}

# Architecture - reference external config
architecture: ${architecture}

# Forward model - reference external config
forward_model:
  _target_: code.model.forward.ForwardModel
  ckpt_path: ../forward_outputs/forward_default/checkpoints/default/model.ckpt
  architecture: ../forward_outputs/forward_default/checkpoints/default/architecture.yaml


# Forward model - reference external config
# forward:
#   model:
#     _target_: code.model.forward.ForwardModel
#     ckpt_path: ../forward_outputs/forward_default/checkpoints/default/model.ckpt
#     architecture: ../forward_outputs/forward_default/checkpoints/default/architecture.yaml
#  transformations:
#
#
#
# forward_model:
#   _target_: torch.nn.Sequential
#   _args_:
#     - Transformation layer
#     - _target_: code.model.forward.ForwardModel
#       ckpt_path: ../forward_outputs/forward_default/checkpoints/default/model.ckpt
#       architecture: ../forward_outputs/forward_default/checkpoints/default/architecture.yaml