_target_: code.model.forward.ForwardModel
_recursive_: false
ckpt_path: /mnt/c/Users/benoi/Documents/Projects/RACCOONN/forward_outputs/forward_clear/checkpoints/modular/model.ckpt
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0005
  weight_decay: 0.0
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.2
  patience: 3
  min_lr: 1.0e-06
  threshold: 0.0
  threshold_mode: abs
loss:
  _target_: code.loss.wrapper.LossTerm
  function:
    _target_: code.loss.probabilistic.CRPS
  output_keys:
  - bt_forward
  - bt_forward_stdev
  target_keys: bt_crtm
pre_process:
  _target_: code.architecture.layer.TransformationsLayers
  _recursive_: false
  transformations: {}
architecture:
  _target_: code.architecture.mlp.MLPModular
  _recursive_: false
  positional_encoding: null
  input_layer:
    _target_: code.architecture.mlp.MLPBlock
    _recursive_: false
    in_features:
      _target_: builtins.sum
      _args_:
      - - _target_: operator.mul
          _args_:
          - _target_: builtins.len
            _args_:
            - - Air temperature
              - Humidity mixing ratio
              - Ozone mixing ratio
          - 127
        - _target_: builtins.len
          _args_:
          - - Ice area fraction
            - Land area fraction
            - Land type index
            - Leaf area index
            - Soil temperature
            - Surface snow area fraction
            - Surface snow thickness
            - Surface ice temperature
            - Surface soil temperature
            - Surface sea temperature
            - Surface snow temperature
            - Surface eastward wind component
            - Surface northward wind component
            - Vegetation area fraction
            - Fraction of condensed water
            - Water area fraction
        - _target_: builtins.len
          _args_:
          - - Sensor scan angle
            - Sensor zenith angle
            - Sensor view angle
            - Sensor azimuth angle
            - Sensor elevation angle
            - Solar azimuth angle
            - Solar zenith angle
    out_features: 512
    activation:
      _target_: code.architecture.activation.Swish
    norm_type: none
    dropout_rate: 0.0
    residual: false
  hidden_layer:
    _target_: code.architecture.mlp.MLPBlocks
    _recursive_: false
    in_features: 512
    out_features: 512
    hidden_features: 512
    n_blocks: 2
    activation:
      _target_: code.architecture.activation.Swish
    norm_type: none
    dropout_rate: 0.0
    residual: false
  output_layer:
    _target_: code.architecture.mlp.HeterogeneousPredictionHeads
    _recursive_: false
    in_features: 512
    out_concat: false
    heads:
    - out_features:
        _target_: builtins.len
        _args_:
        - - Channel 8
          - Channel 9
          - Channel 10
          - Channel 11
          - Channel 12
          - Channel 13
          - Channel 14
          - Channel 15
          - Channel 16
      n_layers: 1
      activation:
        _target_: torch.nn.Sigmoid
      post_process:
        _target_: code.architecture.layer.TransformationsLayer
        transformations:
          normalization:
            _target_: code.data.transformations.min_max
            _partial_: true
            stats:
              _target_: code.preprocessing.statistics.read_statistics_var
              load:
                _target_: code.data.io.load_pkl
                path: code/data/statistics/synthetic_clear.pkl
              key: bt_crtm
              dtype: float32
        inverse_transform: true
    - out_features:
        _target_: builtins.len
        _args_:
        - - Channel 8
          - Channel 9
          - Channel 10
          - Channel 11
          - Channel 12
          - Channel 13
          - Channel 14
          - Channel 15
          - Channel 16
      n_layers: 1
      activation:
        _target_: torch.nn.Softplus
      post_process:
        _target_: code.architecture.layer.AffineLayer
        factor: 1.0
        factor_learnable: true
        value: 0.001
        value_learnable: false
        inverse_transform: true
  hidden_skip: false
  output_skip: false
  inject_encoding_hidden: false
  inject_encoding_output: false
