---
title: DAG
---
flowchart TB
	id0[predict]
	id1[statistics_data]
	id2[data]
	id3[train]
	id4[covariance_R]
	id5[covariance_B]
	style id0 fill:#57D974,stroke-width:2px,color:#333333
	style id1 fill:#57D9AD,stroke-width:2px,color:#333333
	style id2 fill:#D9CA57,stroke-width:2px,color:#333333
	style id3 fill:#5791D9,stroke-width:2px,color:#333333
	style id4 fill:#D99157,stroke-width:2px,color:#333333
	style id5 fill:#D95757,stroke-width:2px,color:#333333
	id3 --> id0
	id2 --> id0
	id1 --> id0
	id2 --> id1
	id5 --> id3
	id2 --> id3
	id1 --> id3
	id4 --> id3
	id2 --> id4
	id2 --> id5
	id1 --> id5
