# Data filters
filters:
  # Cloud/clearsky filter
  cloud:
    # Function
    _target_: data.filters.generate_filter
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Increment estimates for the profile variables
      config: ${data.stage.train.vars.cloud_filter.definition}
    # What the method produces as output
    output:
      # File path to save/load the covariance matrix
      path: ${data.stage.train.vars.cloud_filter.load.path}
      # Save function
      save: ${data.stage.train.vars.cloud_filter.save}
      # Load function
      load: ${data.stage.train.vars.cloud_filter.load}

