# Statistics of the dataset
statistics:
  # Statistics of the training set
  data:
    # Function
    _target_: src.data.statistics.compute_statistics
    _recursive_: false  # Do not instantiate nested objects
    # Exclude variables from the statistics computation
    exclude: ['clear_mask', 'cloud_mask', 'daytime_mask', 'pressure_mask', 'prof_prior']
    # What the method needs as input
    input: ${data.stage.source.variables}
    # Computation parameters
    batch_size: 32
    num_workers: 4
    # What the method produces as output (pickle file)
    output:
      # Path to statistics file
      path: src/data/statistics/statistics.pkl
      # Saving function
      save:
        _target_: src.data.io.save_pkl
        path: ${data.statistics.data.output.path}
      # Loading function
      load:
        _target_: src.data.io.load_pkl
        path: ${data.statistics.data.output.path}
