---
title: DAG
---
flowchart TB
	id0[predict]
	id1[data]
	id2[train]
	style id0 fill:#D9D957,stroke-width:2px,color:#333333
	style id1 fill:#D95757,stroke-width:2px,color:#333333
	style id2 fill:#57D9D9,stroke-width:2px,color:#333333
	id2 --> id0
	id1 --> id0
	id1 --> id2
