# Data filters
filters:
  # Pressure mask (to filter out constant pressure levels)
  pressure_mask:
    # Function
    _target_: code.data.filters.compute_filter
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Call to mask
      mask:
        _target_: code.preprocessing.filters.pressure_mask
        # Statistics of the pressure variable to compute the mask
        stats:
          _target_: code.data.preprocessing.statistics.read_statistics_var
          load: ${data.preprocessing.statistics.data.output.load}
          key: 'pressure'
          dtype: ${data.dtype}
        # Ratio threshold to determine constant pressure levels
        threshold: 0.005

    # What the method produces as output
    output:
      # File path to save/load the covariance matrix
      path: ${....dir}/pressure_mask.npy
      # Save function
      save:
        _target_: numpy.save
        path: ${..path}
      # Load function
      load:
        _target_: code.data.io.load_npy
        path: ${..path}