# Configuration to load multiple preprocessing methods
defaults:
  - recast_cloud2          # First: recast raw data to desired format/precision/filtering
  - slant           # Then: compute slant coordinates
  - statistics      # Then: compute statistics
  - filters         # Then: compute filters
  - covariance      # Finally: compute covariance
  - _self_