# Configuration to load multiple preprocessing methods
defaults:
  - recast          # First: recast raw data to desired format/precision/filtering
  # - slant           # Then: compute slant coordinates
  - statistics      # Then: compute statistics
  - mask            # Then: compute masks
  - covariance      # Finally: compute covariance
  - _self_