mask:
  # Cloud mask (training set)
  cloud_train:
    # Function
    _target_: code.preprocessing.mask.compute_mask
    _recursive_: false  # Do not instantiate nested objects
    # Input data (create mask)
    input:
      _target_: code.preprocessing.mask.cloud_mask
      _args_:
        - ${data.stage.train.variables.prof.load}
    # Output data (save mask)
    output:
      # Save function
      save: ${data.stage.train.variables.cloud_mask.save}
  # Cloud mask (validation set)
  cloud_valid:
    # Function
    _target_: code.preprocessing.mask.compute_mask
    _recursive_: false  # Do not instantiate nested objects
    # Input data (create mask)
    input:
      _target_: code.preprocessing.mask.cloud_mask
      _args_:
        - ${data.stage.valid.variables.prof.load}
    # Output data (save mask)
    output:
      # Save function
      save: ${data.stage.valid.variables.cloud_mask.save}
  # Cloud mask (test set)
  cloud_test:
    # Function
    _target_: code.preprocessing.mask.compute_mask
    _recursive_: false  # Do not instantiate nested objects
    # Input data (create mask)
    input:
      _target_: code.preprocessing.mask.cloud_mask
      _args_:
        - ${data.stage.test.variables.prof.load}
    # Output data (save mask)
    output:
      # Save function
      save: ${data.stage.test.variables.cloud_mask.save}
  # Cloud mask (training set)
  source_cloud_train:
    # Function
    _target_: code.preprocessing.mask.compute_mask
    _recursive_: false  # Do not instantiate nested objects
    # Input data (create mask)
    input:
      _target_: code.preprocessing.mask.cloud_mask
      _args_:
        - ${data.source.train.variables.prof.load}
    # Output data (save mask)
    output:
      # Save function
      save: ${data.source.train.variables.cloud_mask.save}
  # Cloud mask (validation set)
  source_cloud_valid:
    # Function
    _target_: code.preprocessing.mask.compute_mask
    _recursive_: false  # Do not instantiate nested objects
    # Input data (create mask)
    input:
      _target_: code.preprocessing.mask.cloud_mask
      _args_:
        - ${data.source.valid.variables.prof.load}
    # Output data (save mask)
    output:
      # Save function
      save: ${data.source.valid.variables.cloud_mask.save}
  # Cloud mask (test set)
  source_cloud_test:
    # Function
    _target_: code.preprocessing.mask.compute_mask
    _recursive_: false  # Do not instantiate nested objects
    # Input data (create mask)
    input:
      _target_: code.preprocessing.mask.cloud_mask
      _args_:
        - ${data.source.test.variables.prof.load}
    # Output data (save mask)
    output:
      # Save function
      save: ${data.source.test.variables.cloud_mask.save}