# Recast data to new format, spatiotemporal distribution
recast:
  # Training set
  train:
    # Function
    _target_: code.preprocessing.recast.recast_synthetic
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Mask to apply
      mask:
        # Cloud/clear sky
        cloud_mask: false
        clear_mask: true
      # Variables
      variables: ${data.source.train.variables}
    # What the method produces as output
    output:
      # Precision
      dtype: ${data.dtype}
      # Directory of the recast data
      dir: ${data.stage.train.dir}
      # Variables
      variables: ${data.stage.train.variables}
  # Validation set
  valid:
    # Function
    _target_: code.preprocessing.recast.recast_synthetic
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Mask to apply
      mask: ${preprocessing.recast.train.input.mask}
      # Variables
      variables: ${data.source.valid.variables}
    # What the method produces as output
    output:
      # Precision
      dtype: ${data.dtype}
      # Directory of the recast data
      dir: ${data.stage.valid.dir}
      # Variables
      variables: ${data.stage.valid.variables}
  # Test set
  test:
    # Function
    _target_: code.preprocessing.recast.recast_synthetic
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Mask to apply
      mask: ${preprocessing.recast.train.input.mask}
      # Variables
      variables: ${data.source.test.variables}
    # What the method produces as output
    output:
      # Precision
      dtype: ${data.dtype}
      # Directory of the recast data
      dir: ${data.stage.test.dir}
      # Variables
      variables: ${data.stage.test.variables}