defaults:
  - recast

# Recast data to new format, spatiotemporal distribution
recast:
  # Source data
  data:
    # What the method needs as input
    input:
      # Mask to apply
      mask:
        # Spatial domain:
        spatial_domain:
          lat_min: -60.0
          lat_max: 60.0
          lon_min: -180.0
          lon_max: 180.0
        # Temporal domain:
        temporal_window:
          scans_min: 0.0
          scans_max: 1.0
        # Cloud/clear sky
        cloud_mask: false
        clear_mask: true
        # Split
        split:
          # Ratio for split
          ratio:
            train: 0.6
            valid: 0.2
            test: 0.2
          # Seed
          seed: 42
          # Tolerance for edges (degrees)
          tolerance: 0.75