defaults:
  - recast

# Recast data to new format, spatiotemporal distribution
recast:
  # Source data
  data:
    # What the method needs as input
    input:
      # Mask to apply
      mask:
        # Cloud/clear sky
        cloud_mask: true
        clear_mask: false