# Recast data to new format, spatiotemporal distribution
recast:
  # Training set
  train:
    # Function
    _target_: code.preprocessing.recast.recast_synthetic
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Directory of the source data
      dir: ../../../../../../../d/Data/JCSDA/GOES_ML/Train2
      # Mask to apply
      mask:
        # Cloud/clear sky
        cloud_mask: true
        clear_mask: true
      # Variables
      variables:
        # Atmospheric profiles
        prof:
          # Load function
          load:
            _target_: code.data.io.load_npy
            _partial_: true
            path: ${....dir}/prof.npy
        # Latitude
        lat:
          # Loading function
          load:
            _target_: code.data.io.load_latlon
            path: ${....dir}/lat.npy
            scans:
              _target_: ${....scans.load._target_}
              path: ${....scans.load.path}
        # Longitude
        lon:
          # Loading function
          load:
            _target_: code.data.io.load_latlon
            path: ${....dir}/lon.npy
            scans:
              _target_: ${....scans.load._target_}
              path: ${....scans.load.path}
        # Scans
        scans:
          # Loading function
          load:
            _target_: code.data.io.load_scans
            path: ${....dir}/scans.txt
            lat:
              _target_: ${....lat.load._target_}
              path: ${....lat.load.path}
        # Meta data
        meta:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/meta.npy
        # Surface data
        surf:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/surf.npy
        # Observations
        obs:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/obs.npy
        # hofx
        hofx:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/hofx.npy
        # Pressure
        pressure:
          # Loading function
          load:
            _target_: code.data.units.pa_to_hpa
            pressure:
              _target_: code.data.io.load_npy
              path: ${.....dir}/pressure.npy
    # What the method produces as output
    output:
      # Precision
      dtype: ${data.dtype}
      # Directory of the recast data
      dir: ${data.stage.train.dir}
      # Variables
      variables:
        # Atmospheric profiles
        prof:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.train.variables.prof.path}
            dtype: ${data.dtype}
        # Latitude
        lat:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.train.variables.lat.path}
            dtype: ${data.dtype}
        # Longitude
        lon:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.train.variables.lon.path}
            dtype: ${data.dtype}
        # Scans
        scans:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.train.variables.scans.path}
            dtype: ${data.dtype}
        # Meta data
        meta:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.train.variables.meta.path}
            dtype: ${data.dtype}
        # Surface data
        surf:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.train.variables.surf.path}
            dtype: ${data.dtype}
        # Observations
        obs:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.train.variables.obs.path}
            dtype: ${data.dtype}
        # hofx
        hofx:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.train.variables.hofx.path}
            dtype: ${data.dtype}
        # Pressure
        pressure:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.train.variables.pressure.path}
            dtype: ${data.dtype}
        # Cloud mask (addition)
        # cloud_mask:
        #   # Save function
        #   save:
        #     _target_: code.data.io.save_npy
        #     _partial_: true
        #     path: ${data.stage.train.variables.cloud_mask.path}
        #     dtype: bool
        # Daytime mask (addition)
        # daytime_mask:
        #   # Save function
        #   save:
        #     _target_: code.data.io.save_npy
        #     _partial_: true
        #     path: ${data.stage.train.variables.daytime_mask.path}
        #     dtype: bool
  # Validation set
  valid:
    # Function
    _target_: code.preprocessing.recast.recast_synthetic
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Directory of the source data
      dir: ../../../../../../../d/Data/JCSDA/GOES_ML/Val2
      # Variables
      variables:
        # Atmospheric profiles
        prof:
          # Load function
          load:
            _target_: code.data.io.load_npy
            _partial_: true
            path: ${....dir}/prof.npy
        # Latitude
        lat:
          # Loading function
          load:
            _target_: code.data.io.load_latlon
            path: ${....dir}/lat.npy
            scans:
              _target_: ${....scans.load._target_}
              path: ${....scans.load.path}
        # Longitude
        lon:
          # Loading function
          load:
            _target_: code.data.io.load_latlon
            path: ${....dir}/lon.npy
            scans:
              _target_: ${....scans.load._target_}
              path: ${....scans.load.path}
        # Scans
        scans:
          # Loading function
          load:
            _target_: code.data.io.load_scans
            path: ${....dir}/scans.txt
            lat:
              _target_: ${....lat.load._target_}
              path: ${....lat.load.path}
        # Meta data
        meta:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/meta.npy
        # Surface data
        surf:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/surf.npy
        # Observations
        obs:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/obs.npy
        # hofx
        hofx:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/hofx.npy
        # Pressure
        pressure:
          # Loading function
          load:
            _target_: code.data.units.pa_to_hpa
            pressure:
              _target_: code.data.io.load_npy
              path: ${.....dir}/pressure.npy
    # What the method produces as output
    output:
      # Precision
      dtype: ${data.dtype}
      # Directory of the recast data
      dir: ${data.stage.valid.dir}
      # Variables
      variables:
        # Atmospheric profiles
        prof:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.valid.variables.prof.path}
            dtype: ${data.dtype}
        # Latitude
        lat:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.valid.variables.lat.path}
            dtype: ${data.dtype}
        # Longitude
        lon:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.valid.variables.lon.path}
            dtype: ${data.dtype}
        # Scans
        scans:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.valid.variables.scans.path}
            dtype: ${data.dtype}
        # Meta data
        meta:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.valid.variables.meta.path}
            dtype: ${data.dtype}
        # Surface data
        surf:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.valid.variables.surf.path}
            dtype: ${data.dtype}
        # Observations
        obs:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.valid.variables.obs.path}
            dtype: ${data.dtype}
        # hofx
        hofx:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.valid.variables.hofx.path}
            dtype: ${data.dtype}
        # Pressure
        pressure:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.valid.variables.pressure.path}
            dtype: ${data.dtype}
        # Cloud mask (addition)
        # cloud_mask:
        #   # Save function
        #   save:
        #     _target_: code.data.io.save_npy
        #     _partial_: true
        #     path: ${data.stage.valid.variables.cloud_mask.path}
        #     dtype: bool
        # Daytime mask (addition)
        # daytime_mask:
        #   # Save function
        #   save:
        #     _target_: code.data.io.save_npy
        #     _partial_: true
        #     path: ${data.stage.valid.variables.daytime_mask.path}
        #     dtype: bool
  # Test set
  test:
    # Function
    _target_: code.preprocessing.recast.recast_synthetic
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Directory of the source data
      dir: ../../../../../../../d/Data/JCSDA/GOES_ML/Test2
      # Variables
      variables:
        # Atmospheric profiles
        prof:
          # Load function
          load:
            _target_: code.data.io.load_npy
            _partial_: true
            path: ${....dir}/prof.npy
        # Latitude
        lat:
          # Loading function
          load:
            _target_: code.data.io.load_latlon
            path: ${....dir}/lat.npy
            scans:
              _target_: ${....scans.load._target_}
              path: ${....scans.load.path}
        # Longitude
        lon:
          # Loading function
          load:
            _target_: code.data.io.load_latlon
            path: ${....dir}/lon.npy
            scans:
              _target_: ${....scans.load._target_}
              path: ${....scans.load.path}
        # Scans
        scans:
          # Loading function
          load:
            _target_: code.data.io.load_scans
            path: ${....dir}/scans.txt
            lat:
              _target_: ${....lat.load._target_}
              path: ${....lat.load.path}
        # Meta data
        meta:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/meta.npy
        # Surface data
        surf:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/surf.npy
        # Observations
        obs:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/obs.npy
        # hofx
        hofx:
          # Loading function
          load:
            _target_: code.data.io.load_npy
            path: ${....dir}/hofx.npy
        # Pressure
        pressure:
          # Loading function
          load:
            _target_: code.data.units.pa_to_hpa
            pressure:
              _target_: code.data.io.load_npy
              path: ${.....dir}/pressure.npy
    # What the method produces as output
    output:
      # Precision
      dtype: ${data.dtype}
      # Directory of the recast data
      dir: ${data.stage.test.dir}
      # Variables
      variables:
        # Atmospheric profiles
        prof:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.test.variables.prof.path}
            dtype: ${data.dtype}
        # Latitude
        lat:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.test.variables.lat.path}
            dtype: ${data.dtype}
        # Longitude
        lon:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.test.variables.lon.path}
            dtype: ${data.dtype}
        # Scans
        scans:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.test.variables.scans.path}
            dtype: ${data.dtype}
        # Meta data
        meta:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.test.variables.meta.path}
            dtype: ${data.dtype}
        # Surface data
        surf:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.test.variables.surf.path}
            dtype: ${data.dtype}
        # Observations
        obs:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.test.variables.obs.path}
            dtype: ${data.dtype}
        # hofx
        hofx:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.test.variables.hofx.path}
            dtype: ${data.dtype}
        # Pressure
        pressure:
          # Save function
          save:
            _target_: code.data.io.save_npy
            _partial_: true
            path: ${data.stage.test.variables.pressure.path}
            dtype: ${data.dtype}
        # Cloud mask (addition)
        # cloud_mask:
        #   # Save function
        #   save:
        #     _target_: code.data.io.save_npy
        #     _partial_: true
        #     path: ${data.stage.test.variables.cloud_mask.path}
        #     dtype: bool
        # Daytime mask (addition)
        # daytime_mask:
        #   # Save function
        #   save:
        #     _target_: code.data.io.save_npy
        #     _partial_: true
        #     path: ${data.stage.test.variables.daytime_mask.path}
        #     dtype: bool