# Compute slant path coordinates
slant:
  # Training set
  train:
    # Function
    _target_: code.preprocessing.slant.compute_slant_path
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Coordinates
      lat: ${data.stage.train.vars.lat}
      lon: ${data.stage.train.vars.lon}
      pressure: ${data.stage.train.vars.pressure}
      # Meta data
      meta: ${data.stage.train.vars.meta}
      # Profiles
      prof: ${data.stage.train.vars.prof}
    output:
      lat:
        # Output path
        path: ${data.stage.train.dir}/lat_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.train.output.lat.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.train.output.lat.path}
            - ${data.dtype}
      lon:
        # Output path
        path: ${data.stage.train.dir}/lon_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.train.output.lon.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.train.output.lon.path}
            - ${data.dtype}
      z:
        # Output path
        path: ${data.stage.train.dir}/z_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.train.output.z.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.train.output.z.path}
            - ${data.dtype}
      x:
        # Output path
        path: ${data.stage.train.dir}/x_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.train.output.x.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.train.output.x.path}
            - ${data.dtype}
      y:
        # Output path
        path: ${data.stage.train.dir}/y_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.train.output.y.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.train.output.y.path}
            - ${data.dtype}
  # Validation set
  valid:
    # Function
    _target_: code.data.slant.compute_slant_path
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Coordinates
      lat: ${data.stage.valid.vars.lat}
      lon: ${data.stage.valid.vars.lon}
      pressure: ${data.stage.valid.vars.pressure}
      # Meta data
      meta: ${data.stage.valid.vars.meta}
      # Profiles
      prof: ${data.stage.valid.vars.prof}
    output:
      lat:
        # Output path
        path: ${data.stage.valid.dir}/lat_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.valid.output.lat.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.valid.output.lat.path}
            - ${data.dtype}
      lon:
        # Output path
        path: ${data.stage.valid.dir}/lon_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.valid.output.lon.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.valid.output.lon.path}
            - ${data.dtype}
      z:
        # Output path
        path: ${data.stage.valid.dir}/z_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.valid.output.z.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.valid.output.z.path}
            - ${data.dtype}
      x:
        # Output path
        path: ${data.stage.valid.dir}/x_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.valid.output.x.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.valid.output.x.path}
            - ${data.dtype}
      y:
        # Output path
        path: ${data.stage.valid.dir}/y_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.valid.output.y.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.valid.output.y.path}
            - ${data.dtype}
  # Test set
  test:
    # Function
    _target_: code.data.slant.compute_slant_path
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Coordinates
      lat: ${data.stage.test.vars.lat}
      lon: ${data.stage.test.vars.lon}
      pressure: ${data.stage.test.vars.pressure}
      # Meta data
      meta: ${data.stage.test.vars.meta}
      # Profiles
      prof: ${data.stage.test.vars.prof}
    output:
      lat:
        # Output path
        path: ${data.stage.test.dir}/lat_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.test.output.lat.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.test.output.lat.path}
            - ${data.dtype}
      lon:
        # Output path
        path: ${data.stage.test.dir}/lon_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.test.output.lon.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.test.output.lon.path}
            - ${data.dtype}
      z:
        # Output path
        path: ${data.stage.test.dir}/z_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.test.output.z.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.test.output.z.path}
            - ${data.dtype}
      x:
        # Output path
        path: ${data.stage.test.dir}/x_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.test.output.x.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.test.output.x.path}
            - ${data.dtype}
      y:
        # Output path
        path: ${data.stage.test.dir}/y_slant.npy
        # Save function
        save:
          _target_: numpy.save
          _partial_: true
          _args_:
            - ${preprocessing.slant.test.output.y.path}
        # Load function
        load:
          _target_: code.data.io.load_npy
          _args_:
            - ${preprocessing.slant.test.output.y.path}
            - ${data.dtype}