# Compute slant path coordinates
slant:
  # Training set
  train:
    # Function
    _target_: code.preprocessing.slant.compute_slant_path
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Coordinates
      lat: ${data.stage.train.variables.lat}
      lon: ${data.stage.train.variables.lon}
      pressure: ${data.stage.train.variables.pressure}
      # Meta data
      meta: ${data.stage.train.variables.meta}
      # Profiles
      prof: ${data.stage.train.variables.prof}
    output:
      # Coordinates
      lat: ${data.stage.train.variables.lat_slant}
      lon: ${data.stage.train.variables.lon_slant}
      z: ${data.stage.train.variables.z_slant}
      x: ${data.stage.train.variables.x_slant}
      y: ${data.stage.train.variables.y_slant}
  # Validation set
  valid:
    # Function
    _target_: code.preprocessing.slant.compute_slant_path
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Coordinates
      lat: ${data.stage.valid.variables.lat}
      lon: ${data.stage.valid.variables.lon}
      pressure: ${data.stage.valid.variables.pressure}
      # Meta data
      meta: ${data.stage.valid.variables.meta}
      # Profiles
      prof: ${data.stage.valid.variables.prof}
    output:
      # Coordinates
      lat: ${data.stage.valid.variables.lat_slant}
      lon: ${data.stage.valid.variables.lon_slant}
      z: ${data.stage.valid.variables.z_slant}
      x: ${data.stage.valid.variables.x_slant}
      y: ${data.stage.valid.variables.y_slant}
  # Test set
  test:
    # Function
    _target_: code.preprocessing.slant.compute_slant_path
    _recursive_: false  # Do not instantiate nested objects
    # What the method needs as input
    input:
      # Coordinates
      lat: ${data.stage.test.variables.lat}
      lon: ${data.stage.test.variables.lon}
      pressure: ${data.stage.test.variables.pressure}
      # Meta data
      meta: ${data.stage.test.variables.meta}
      # Profiles
      prof: ${data.stage.test.variables.prof}
    output:
      # Coordinates
      lat: ${data.stage.test.variables.lat_slant}
      lon: ${data.stage.test.variables.lon_slant}
      z: ${data.stage.test.variables.z_slant}
      x: ${data.stage.test.variables.x_slant}
      y: ${data.stage.test.variables.y_slant}