# Note: The order of defaults determines the order in which configs override each other.
defaults:
  - paths: default
  - hydra: default
  - data: inverse_default
  - preprocessing: inverse_default
  - loader: default
  - architecture: mlp_modular
  - loss: var
  - optimizer: default
  - scheduler: default
  - model: inverse_default
  - callback: inverse_default
  - logger: default
  - trainer: cpu
  - _self_
