# CRPS Loss for forward model using LossTerm
_target_: code.loss.wrapper.LossTerm
function:
  _target_: code.loss.probabilistic.CRPS
output_keys: ['bt_forward', 'bt_forward_stdev']
target_keys: 'bt_crtm'

