# Variational Loss for inverse problems
_target_: inverse.model.loss.VarLoss

# Forward model to compute the model equivalent of the observations
forward_model:
  _target_: inverse.model.loss.ForwardModel
  dtype: ${data.dtype}
  prof_norm: null

# Weights for observation (obs), model, and boundary condition (bcs) errors
lambda_obs: 0.0
lambda_model: 1.0
lambda_bcs: 1.0

# Loss term for observations
loss_obs:
  _target_: inverse.model.loss.MSE

# Loss term for model variables
loss_model:
  _target_: inverse.model.loss.MSE

# Loss term for boundary conditions
loss_bcs:
  _target_: inverse.model.loss.MSE

# Pressure filter: Consider only pressure levels with non-zero variance
pressure_filter: ${data.pressure_filter.load}

