# Data loader configuration for model training
_target_: code.loader.dataloader.Dataloader
_recursive_: false
batch_size: 32  # Batch size for training
num_workers: 16  # Number of workers for data loading
persistent_workers: true  # Keep workers alive between epochs
pin_memory: true  # Pin memory for faster data transfer to GPU

# Stage-specific data loader configurations
stage:
  # Training stage
  train:
    _target_: code.loader.dataset.MultivariateDatasets
    input:
      _target_: code.loader.dataset.MultivariateDataset
      variables: ${extract:${data.stage.train.variables},${data.select_input}}
    target:
      _target_: code.loader.dataset.MultivariateDataset
      variables: ${extract:${data.stage.train.variables},${data.select_target}}
    context:
      _target_: code.loader.dataset.MultivariateDataset
      variables: ${extract:${data.stage.train.variables},${data.select_context}}
  # Validation stage
  valid:
    _target_: ${loader.stage.train._target_}
    input:
      _target_: ${loader.stage.train.input._target_}
      variables: ${extract:${data.stage.valid.variables},${data.select_input}}
    target:
      _target_: ${loader.stage.train.target._target_}
      variables: ${extract:${data.stage.valid.variables},${data.select_target}}
    context:
      _target_: ${loader.stage.train.context._target_}
      variables: ${extract:${data.stage.valid.variables},${data.select_context}}
  # Test stage
  test:
    _target_: ${loader.stage.train._target_}
    input:
      _target_: ${loader.stage.train.input._target_}
      variables: ${extract:${data.stage.test.variables},${data.select_input}}
    target:
      _target_: ${loader.stage.train.target._target_}
      variables: ${extract:${data.stage.test.variables},${data.select_target}}
    context:
      _target_: ${loader.stage.train.context._target_}
      variables: ${extract:${data.stage.test.variables},${data.select_context}}
    output:
      _target_: ${loader.stage.train.output._target_}
      variables: ${extract:${data.stage.test.output},${data.select_output}}
  # Prediction stage
  predict:
    _target_: ${loader.stage.train._target_}
    input:
      _target_: ${loader.stage.train.input._target_}
      variables: ${extract:${data.stage.predict.variables},${data.select_input}}
    output:
      _target_: ${loader.stage.train.output._target_}
      variables: ${extract:${data.stage.predict.output},${data.select_output}}