_target_: code.architecture.legacy.CRTMArchitecture
_recursive_: true
nprofvars:
  _target_: builtins.len
  _args_:
  - - Air temperature
    - Humidity mixing ratio
    - Ozone mixing ratio
nsurfvars:
  _target_: builtins.len
  _args_:
  - - Ice area fraction
    - Land area fraction
    - Land type index
    - Leaf area index
    - Soil temperature
    - Surface snow area fraction
    - Surface snow thickness
    - Surface ice temperature
    - Surface soil temperature
    - Surface sea temperature
    - Surface snow temperature
    - Surface eastward wind component
    - Surface northward wind component
    - Vegetation area fraction
    - Fraction of condensed water
    - Water area fraction
nmetavars:
  _target_: builtins.len
  _args_:
  - - Sensor scan angle
    - Sensor zenith angle
    - Sensor view angle
    - Sensor azimuth angle
    - Sensor elevation angle
    - Solar azimuth angle
    - Solar zenith angle
nlevels: 127
nnodes_bt: 512
nhidden_bt: 3
dropout_rate: 0.0
bt_norm_max: 355
bt_norm_min: 180
std_output_activation_offset: 0.001
std_scale_trainable: true
