# CRTM Smooth Architecture (with skip connections)
_target_: code.architecture.CRTMSmoothArchitecture
_recursive_: false

# Number of input variables
nprofvars: ${data.nprofvars}
nsurfvars: ${data.nsurfvars}
nmetavars: ${data.nmetavars}
nlevels: ${data.nlevels}

# Neural network parameters
nnodes_bt: 512
nhidden_bt: 3
dropout_rate: 0.0

# Output activation parameters
bt_norm_max: ${data.bt_norm_max}
bt_norm_min: ${data.bt_norm_min}
std_output_activation_offset: 0.001
std_scale_trainable: true

