_target_: code.architecture.mlp.MLPModular
_recursive_: false

# Positional encoding
positional_encoding:
  _target_: code.architecture.encoding.GaussianPositionalEncoding
  _recursive_: true
  sigma: 3.
  d_input:
    _target_: builtins.len
    _args_:
      - ${data.select_input}

# Input layer
input_layer:
  _target_: code.architecture.mlp.MLPBlock
  _recursive_: false
  in_features: null  # Set by positional encoding output
  out_features: 128
  activation:
    _target_: code.architecture.activation.Sine
    w0: 3.
  norm_type: none
  dropout_rate: 0.1
  residual: false

# Hidden layers
hidden_layer:
  _target_: code.architecture.mlp.MLPBlocks
  _recursive_: false
  in_features: ${.hidden_features}
  out_features: ${.hidden_features}
  hidden_features: 128
  n_blocks: 2
  activation:
    _target_: code.architecture.activation.Sine
    w0: 3.
  norm_type: none
  dropout_rate: 0.1
  residual: false

# Output layer
output_layer:
  _target_: code.architecture.mlp.HomogeneousPredictionHeads
  _recursive_: false
  n_heads: ${data.stage.train.variables.prof_inverse.n}
  out_concat: true
  head:
    _target_: code.architecture.mlp.PredictionHead
    _recursive_: false
    in_features: ${...hidden_layer.out_features}
    hidden_features: ${...hidden_layer.out_features}
    out_features: 1
    n_blocks: 2
    activation:
      _target_: code.architecture.activation.Sine
      w0: 3.
    final_activation:
      _target_: torch.nn.Identity
    norm_type: none
    dropout_rate: 0.
    residual: false

# Skip connections
hidden_skip: false
output_skip: false
inject_encoding_hidden: false
inject_encoding_output: false